Выполни на питоне 2 задач, каждую задачу оформи отдельной программой:
Задание 1: Базовая обработка исключений

Напиши функцию safe_divide, которая принимает два аргумента: a и b. Функция должна пытаться делить a на b и возвращать результат. 
Если произойдет ошибка деления на ноль (ZeroDivisionError), функция должна возвращать None вместо возникновения исключения. 
Продемонстрируй работу функции на нескольких примерах, включая деление на ноль.



Задание 2: Обработка множества видов исключений

Напиши программу, которая запрашивает у пользователя ввести целое число, а затем пытается преобразовать введенное значение в целочисленный тип. 
Используй блок try-except, чтобы корректно обработать возможные исключения, которые могут возникнуть в этом процессе, включая ValueError. 
В случае ValueError выведи сообщение "Невозможно преобразовать введенное значение в целое число". Программа должна просить пользователя попробовать ввести число еще раз. 
Убедись, что программа корректно работает с корректным вводом, и продемонстрируй ее поведение на некорректном вводе.




